site_name: zhehaya
theme:
  name: readthedocs
nav: 
  - 主页: index.md
  - 算法学习:
    - 字符串算法学习笔记: 算法学习/字符串算法学习笔记.md
    - NOIP备考记录杂: 算法学习/题目记录（一直更新.md
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

